/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import conexion.Control;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author awelo
 */
public class PnlLogeado extends javax.swing.JPanel {

    private javax.swing.JFrame frame;
    private String user;
    /**
     * Creates new form PnlLogeado
     */
    public PnlLogeado(javax.swing.JFrame frame) {
        this.frame = frame;
        initComponents();
    }
    
    public void setValores (String[] datos){
        
        lblNombre.setText(datos[0]+"    "+datos[1]);
        user=datos[0];
    }
    
    private float calcularHora(java.util.Date horIn, java.util.Date horFin){
        int horas= horIn.getHours();
        int minutos= horIn.getMinutes();
        int segundos= horIn.getSeconds();
        
        int horaInto= minutos*60+horas*60*60+segundos;
        
        int horas2= horFin.getHours();
        int minutos2=horFin.getMinutes();
        int segundos2=horFin.getSeconds();
        
        int horaFinto= minutos*60+horas*60*60+segundos;
        
        int totalHoras=horaFinto-horaInto;
        
        float hor=totalHoras/60;
        hor=hor/60;
        
        return hor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogOut)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut)
                    .addComponent(lblNombre))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "¿Estas seguro(a) que deseas cerrar sesión?")==0){
            ConfirmLogout confirmar = new ConfirmLogout(new javax.swing.JFrame(), true);
            confirmar.setVisible(true);
            if(!confirmar.getPass().equals("")){
                Control controla= new Control();
                String contra="";
                ResultSet obtener= controla.darLogonFilt(Integer.parseInt(user));
                try {
                    while(obtener.next()){
                        contra=obtener.getString(4);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(PnlLogeado.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(confirmar.getPass().equals(contra)){
                    java.util.Calendar calendario = new java.util.GregorianCalendar();
                    java.sql.Time salida = new java.sql.Time(calendario.get(calendario.HOUR), calendario.get(calendario.MINUTE), calendario.get(calendario.SECOND));
                    java.util.Date fechas = (java.util.Date) salida;
                    java.util.Date entrada = controla.darInicio(Integer.parseInt(user));
                    //float horasTrab= calcularHora(entrada, fechas);
                    //System.out.println(horasTrab);
                    if(controla.logOut(user)==1){
                        frame.dispose();
                        JOptionPane.showMessageDialog(this, "Has cerrado Sesión");
                        Login logear = new Login();
                        logear.setLocationRelativeTo(null);
                        logear.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(this, "No se ha podido cerrar Sesión");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "La contraseña es incorrecta");
                }
            }else{
                JOptionPane.showMessageDialog(this, "La contraseña es incorrecta");
            }
        }
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
    public String getUser(){
        return user;
    }
}
